#!/bin/sh
show_menu(){
    NORMAL=`echo "\033[m"`
    MENU=`echo "\033[36m"` #Blue
    NUMBER=`echo "\033[33m"` #yellow
    FGRED=`echo "\033[41m"`
    RED_TEXT=`echo "\033[31m"`
    ENTER_LINE=`echo "\033[33m"`
    echo -e "${MENU}*********************************************${NORMAL}"
    echo -e "${MENU}**${NUMBER} 0)${MENU} Update Arch Mirrorlist ${NORMAL}"
    echo -e "${MENU}**${NUMBER} 1)${MENU} Show last 20 packages installed ${NORMAL}"
    echo -e "${MENU}**${NUMBER} 2)${MENU} List packages marked for upgrade with their download size ${NORMAL}"
    echo -e "${MENU}**${NUMBER} 3)${MENU} List all explicitly installed packages: ${NORMAL}"
    echo -e "${MENU}**${NUMBER} 4)${MENU} List all native packages (installed from the sync database(s)): ${NORMAL}"
    echo -e "${MENU}**${NUMBER} 5)${MENU} Update Arch Packages ${NORMAL}"
    echo -e "${MENU}**${NUMBER} 6)${MENU} List all installed packages and their individual sizes ${NORMAL}"
    echo -e "${MENU}**${NUMBER} 7)${MENU} List all installed packages unrequired by other packages and which are not in the base or base-devel 
      groups with descriptions ${NORMAL}"
    echo -e "${MENU}**${NUMBER} 8)${MENU} For recursively removing orphans and their configuration files ${NORMAL}"
    echo -e "${MENU}**${NUMBER} 9)${MENU} Show the tree of local installed packages ${NORMAL}"
    echo -e "${MENU}*********************************************${NORMAL}"
    echo -e "${ENTER_LINE}Please enter a menu option or ${RED_TEXT}enter to exit. ${NORMAL}"
    read  -sn1 opt 
    
}
function option_picked() {
    COLOR='\033[01;31m' # bold red
    RESET='\033[00;00m' # normal white
    MESSAGE=${@:-"${RESET}Error: No message passed"}
    echo -e "${COLOR}${MESSAGE}${RESET}"
}

clear
show_menu
while [ opt != '' ]
    do
    if [[ $opt = "" ]]; then 
            exit;
    else
        case $opt in
        0) clear;
           option_picked "Option 0 Picked";
           sudo reflector -c "GB" -f 12 -l 10 -n 12 --save /etc/pacman.d/mirrorlist; 
           echo "Arch Linux mirrorlist generated by Reflector"
           show_menu;
           ;;

   
        1) clear;
           option_picked "Option 1 Picked";
           expac --timefmt='%Y-%m-%d %T' '%l\t%n' | sort | tail -n 20; 
           show_menu;
           ;;

        2) clear;
            option_picked "Option 2 Picked"
            pacman -Quq|xargs expac -S -H M '%k\t%n' ; echo -e ; pacman -Qu | column -t
            show_menu
            ;;

        3) clear;
            option_picked "Option 3 Picked";
            pacman -Qe | less;
            show_menu;
            ;;

        4) clear;
            option_picked "Option 4 Picked";
            pacman -Qn | less;
            show_menu;
            ;;


	5) clear;
	    option_picked "Option 5 Picked";
	    sudo pacman -Syu;
	    show_menu;
	    ;;
	
	6) clear;
            option_picked "Option 6 Picked";
            pacman -Qi | awk '/^Name/{name=$3} /^Installed Size/{print $4$5, name}' | sort -h | less;
            show_menu;
            ;;

        7) clear;
            option_picked "Option 7 Picked";
            expac -HM '%-20n\t%10d' $(comm -23<(pacman -Qqt | sort)<(pacman -Qqg base base-devel | sort)) | less;
            show_menu;
            ;;

	8) clear;
            option_picked "Option 8 Picked";
            sudo pacman -Rns $(pacman -Qtdq);
            show_menu;
            ;;
        9) clear;
            option_picked "Option 9 Picked";
            pacman -Qi | less;
            show_menu;
            ;;


        x)exit;
        ;;

        \n)exit;
        ;;

        *)clear;
        option_picked "Pick an option from the menu";
        show_menu;
        ;;
    esac
fi
done
